name: 'EUserv Auto Extend'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '1 0 */4 * *'

jobs:
  auto_renew:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2

      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: 'Install dependencies'
        run: |
          pip install requests beautifulsoup4
      - name: 'Auto_renew'
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          YD_EMAIL: ${{ secrets.YD_EMAIL }}
          YD_APP_PWD: ${{ secrets.YD_APP_PWD }}
          TRUECAPTCHA_USERID: ${{ secrets.TRUECAPTCHA_USERID }}
          TRUECAPTCHA_APIKEY: ${{ secrets.TRUECAPTCHA_APIKEY }}
          MAILPARSER_DOWNLOAD_URL_ID: ${{ secrets.MAILPARSER_DOWNLOAD_URL_ID }}
        run: python eu.py
